version: '3'
services:
    database:
        image: postgres
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    admin:
        image: adminer
        restart: always
        depends_on:
            - database
        ports:
            - 8080:8080
